# https://taskfile.dev

version: '3'

tasks:
  generate:
    aliases:
      - gen-auth
    cmds:
      - protoc -I proto proto/auth/auth.proto --go_out=./gen/v1/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/v1/go/ --go-grpc_opt=paths=source_relative
