version: '3'

vars:
  PROTO_DIR: proto
  OUT_DIR: gen/go

tasks:
  gen:
    desc: "Generate Go code from proto file. Usage: task gen -- FILE=auth/auth.proto"
    vars:
      FILE: '{{.FILE | default "auth/auth.proto"}}'
    cmds:
      - powershell -Command "New-Item -ItemType Directory -Force -Path '{{.OUT_DIR}}'"
      - powershell -Command "protoc -I {{.PROTO_DIR}} {{.PROTO_DIR}}/{{.FILE}} --go_out={{.OUT_DIR}} --go_opt=paths=source_relative --go-grpc_out={{.OUT_DIR}} --go-grpc_opt=paths=source_relative"
    platforms: [windows]
